---
title: "inference-with-moving-block-bootstrap"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{inference-with-moving-block-bootstrap}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(kilianr)
```

To render the vignette:
devtools::build_rmd("vignettes/my-vignette.Rmd")


# Mechanics of wild bootstrap

```{r}
# Create data to look through
yview <- kilianLutkepohlCh12Figure12_5 |> 
  mutate(date_prefix = paste0(year(date), "-", format(date, "%m")),
         oil_supply = paste0(date_prefix, "-", "oilsupply"),
         agg_demand = paste0(date_prefix, "-", "aggdemand"),
         rpoil = paste0(date_prefix, "-", "rpoil")) |> 
  select(oil_supply, agg_demand, rpoil)


t_yview <- nrow(yview)
p_yview <- 3
q_yview <- 3

y <- t(yview)
Y <- y[, p_yview:t_yview]
for (i in 1:(p_yview - 1)) {
  Y <- rbind(Y, y[, (p_yview - i):(t_yview - i)])
}
Y

Uhat <- y

rUtilde <- matrix(0, nrow = q_yview * p_yview, ncol = t_yview - p_yview)
rY <- matrix(0, q_yview * p_yview, t_yview - p_yview + 1)
len <- 4
pos <- runif(1, min = 0, max = 1) * (t_yview - p_yview + 1) + 1
rY[, 1] <- Y[, pos]

upos <- ceiling(runif(1) * ((t_yview - p_yview) - len + 1))
# rUtilde[, 1:len] <- Uhat[,upos:(upos + len - 1)]
rUtilde <- Uhat[,upos:(upos + len - 1)]

for (k in 1:ceiling((t_yview - p_yview) / len)) {
  upos <- ceiling(runif(1) * ((t_yview - p_yview) - len + 1))
  print(upos)
  rUtilde <- cbind(rUtilde, Uhat[, upos:(upos + len - 1)])
}
```
